version: "3.9"
services:
  postgres:
    env_file: .env
    build:
      context: ./postgre-sql
      dockerfile: Dockerfile
      args:
        - POSTGRES_DB:${POSTGRES_DB}
        - POSTGRES_USER:${POSTGRES_USER}
        - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
        - POSTGRES_HOST:${POSTGRES_HOST}
        
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    
  server:
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PORT:${PORT}
        - CRYPT_SALT:${CRYPT_SALT}
        - JWT_SECRET_KEY:${JWT_SECRET_KEY}
        - JWT_SECRET_REFRESH_KEY:${JWT_SECRET_REFRESH_KEY}
        - TOKEN_EXPIRE_TIME:${TOKEN_EXPIRE_TIME}
        - TOKEN_REFRESH_EXPIRE_TIME:${TOKEN_REFRESH_EXPIRE_TIME}
    ports:
      - ${PORT}:${PORT}
    command: ["npm", "start"]
    depends_on:
      - postgres