version: "3.9"
services:
  postgres:
    env_file: .env
    container_name: ${POSTGRES_HOST}
    build:
      context: ./postgre-sql
      dockerfile: Dockerfile
      args:
        - POSTGRES_HOST:${POSTGRES_HOST}
        - POSTGRES_DB:${POSTGRES_DB}
        - POSTGRES_USER:${POSTGRES_USER}
        - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
        - POSTGRES_HOST:postgres
        - PG_CONTAINER_NAME:library
        - PGDATA='/data/library'
    volumes:
      - home:/data/library
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - local
    logging:
      driver: none
  server:
    container_name: server
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - PORT:${PORT}
        - CRYPT_SALT:${CRYPT_SALT}
        - JWT_SECRET_KEY:${JWT_SECRET_KEY}
        - JWT_SECRET_REFRESH_KEY:${JWT_SECRET_REFRESH_KEY}
        - TOKEN_EXPIRE_TIME:${TOKEN_EXPIRE_TIME}
        - TOKEN_REFRESH_EXPIRE_TIME:${TOKEN_REFRESH_EXPIRE_TIME}
    volumes:
      - home:/data/server
    ports:
      - ${PORT}:${PORT}
    command: npm run start:prod
    depends_on:
      - postgres
    networks:
      - local
    logging:
      driver: none
networks:
  local:
volumes:
    home: